version: '3.8'

services:
  lms-forum:
    container_name: lms-forum
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
